"""adds fixtures table

Revision ID: 44d3ca27214f
Revises: d4e79711dab7
Create Date: 2023-12-18 13:04:54.436956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d3ca27214f'
down_revision = 'd4e79711dab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_round', sa.Integer(), nullable=True),
    sa.Column('fixture_date', sa.DateTime(), nullable=True),
    sa.Column('fixture_home_team', sa.String(), nullable=True),
    sa.Column('fixture_away_team', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixtures'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
