"""add actual scores and is_completed to fixtures

Revision ID: 78b25607af51
Revises: 500d06a71946
Create Date: 2026-01-24 10:48:42.653571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b25607af51'
down_revision = '500d06a71946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_home_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_away_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('is_completed')
        batch_op.drop_column('actual_away_score')
        batch_op.drop_column('actual_home_score')

    # ### end Alembic commands ###
