"""remove game_id foreign key from users table

Revision ID: d4e79711dab7
Revises: bc3b3b0103ce
Create Date: 2023-12-12 15:23:33.403030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e79711dab7'
down_revision = 'bc3b3b0103ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_game_id_games', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_game_id_games', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###
